# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      path: homepage
      class: first
    - label: Over ons
      path: over-ons
      submenu:
          - label: Historie
            path: historie
          - label: Heden
            path: heden
    - label: Assortiment
      path: assortiment
    - label: Teelt
      path: teelt
      submenu:
        - label: Planten
          path: planten
        - label: Selectie
          path: selectie
        - label: Koppen en beregenen
          path: koppen-en-beregenen
        - label: Rooien
          path: rooien
        - label: Pellen en verwerken
          path: pellen-en-verwerken
    - label: Broei
      path: broei
    - label: Export
      path: export
    - label: Acties
      path: acties
      submenu:
        - label: Tulpen
          path: tulpen
        - label: Droogverkoop
          path: droogverkoop
        - label: Bollenmanden
          path: bollenmanden
        - label: Bolchrysanten
          path: bolchrysanten
        - label: Overige acties
          path: overige-acties
    - label: Contact
      path: contact
