# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      path: homepage
      class: first
    - label: Over ons
      path: pages/over-ons
      submenu:
          - label: Historie
            path: historie
          - label: Heden
            path: heden
    - label: Teelt
      path: teelt
    - label: Broei
      path: broei
    - label: Export
      path: export
    - label: Acties
      path: acties
    - label: Contact
      path: contact
